# Generated by Django 6.0.5 on 2026-05-16 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_category', models.CharField(max_length=50)),
                ('current_word_index', models.IntegerField(default=0)),
                ('completed_words', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_puzzle_states', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Puzzle States',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'mood_category')},
            },
        ),
    ]
